apiVersion: apps/v1
kind: Deployment
metadata:
  name: leshan
  labels:
    app: leshan
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leshan
  template:
    metadata:
      labels:
        app: leshan
    spec:
      containers:
        - name: leshan
          image: edgenesis/lwm2m-demo-leshan-server
          ports:
            - containerPort: 5683
              protocol: TCP
            - containerPort: 5683
              protocol: UDP
            - containerPort: 5684
              protocol: TCP
            - containerPort: 5684
              protocol: UDP
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: leshan-storage
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
      volumes:
        - name: leshan-storage
          persistentVolumeClaim:
            claimName: pvc-leshan

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-leshan
  namespace: default
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/user/k8s/volumes"  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-leshan
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual

---
apiVersion: v1
kind: Service
metadata:
  name: leshan-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30002 
  selector:
    app: leshan
