apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nodered-service","namespace":"default"},"spec":{"ports":[{"port":1880,"protocol":"TCP","targetPort":1880}],"selector":{"app":"nodered"},"type":"LoadBalancer"}}
  name: nodered-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 1880
      protocol: TCP
      targetPort: 1880
      nodePort: 30000
  selector:
    app: nodered
---

apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30001  # Choose an available port in the NodePort range
  selector:
    app: grafana
